return {
    rename = require("LspUI.rename"),
    lightbulb = require("LspUI.lightbulb"),
    code_action = require("LspUI.code_action"),
    diagnostic = require("LspUI.diagnostic"),
    hover = require("LspUI.hover"),
    definition = require("LspUI.definition"),
    type_definition = require("LspUI.type_definition"),
    declaration = require("LspUI.declaration"),
    implementation = require("LspUI.implementation"),
    reference = require("LspUI.reference"),
    inlay_hint = require("LspUI.inlay_hint"),
    call_hierarchy = require("LspUI.call_hierarchy"),
    signature = require("LspUI.signature"),
    jump_history = require("LspUI.jump_history"),
}
